
#General settings
[general]
	#A list of buildings that are safe(r)
	excludedBuildings = []
	#List of mobs that can spawn in buildings together with their rarity
	mobs = [".3=minecraft:zombie", ".3=minecraft:zombie_villager", ".3=minecraft:husk", ".2=graveyard:ghoul", ".1=hmag:zombie_girl", ".1=hmag:drowned_girl"]
	#List of weapons that the mobs can have together with their rarity
	randomWeapons = [".3=null", ".3=cgm:pistol", ".3=minecraft:stone_sword", ".3=cgm:rifle"]
	#List of helmets that the mobs can have together with their rarity
	randomHelmets = [".3=null", ".3=immersive_armors:bone_helmet", ".3=immersive_armors:wooden_helmet"]
	#List of chestplates that the mobs can have together with their rarity
	randomChestplates = [".3=null", ".3=immersive_armors:bone_chestplate", ".3=immersive_armors:wooden_chestplate"]
	#List of leggings that the mobs can have together with their rarity
	randomLeggings = [".3=null", ".3=immersive_armors:bone_leggings", ".3=immersive_armors:wooden_leggings"]
	#List of boots that the mobs can have together with their rarity
	randomBoots = [".3=null", ".3=immersive_armors:bone_boots", ".3=immersive_armors:wooden_boots"]
	#List of effects that a mob can have. Note that multiple effects are possible
	randomEffects = [".1=minecraft:regeneration,1", ".1=minecraft:speed,1", ".1=minecraft:fire_resistance,1"]
	#List of console commands to execute the first time a building is entered
	commandFirstTime = []
	#List of console commands to execute every time a building is entered
	commandEntered = []
	#List of console commands to execute when a building is cleared
	commandCleared = []
	#This message is given when the player tries to open a chest in a haunted building
	messageUnsafeBuilding = "No time to open this chest! Is there something behind you?!?"
	#This message is given when the player enters a haunted building for the first time
	messageBuildingHaunted = "You hear something. This building is probably crawling with undead!"
	#This message is given when the player clears a building
	messageBuildingCleared = "You feel this building is free of the undead."
	#This message is given when the player is halfway clearing a building
	messageBuildingHalfway = "They keep coming, but you can beat them. Keep going!"
	#The amount of ticks that the server waits before checking for new spawns
	#Range: 1 ~ 1000000
	serverTickTimeout = 200
	#The maximum amount of entities that can spawn near each other (of the same type)
	#Range: 1 ~ 200
	spawnMaxNearby = 6
	#The minimum distance between the player and newly spawned mobs
	#Range: 0.0 ~ 16.0
	minSpawnDistance = 8.0
	#The minimum health bonus that the mob will get
	#Range: 0.009999999776482582 ~ 10000.0
	minHealthBonus = 0.009999999776482582
	#The maximum health bonus that the mob will get
	#Range: 0.009999999776482582 ~ 10000.0
	maxHealthBonus = 1.5
	#The minimum damage bonus that the mob will get
	#Range: 0.009999999776482582 ~ 10000.0
	minDamageBonus = 0.009999999776482582
	#The maximum damage bonus that the mob will get
	#Range: 0.009999999776482582 ~ 10000.0
	maxDamageBonus = 1.5
	#The chance that a building is haunted
	#Range: 0.0 ~ 1.0
	hauntedChance = 0.700000011920929
	#The minimum amount of mobs that are spawned by a haunted building
	#Range: 1 ~ 10000
	minMobs = 3
	#The maximum amount of mobs that are spawned by a haunted building
	#Range: 1 ~ 10000
	maxMobs = 6
	#The chance that a building is haunted. This version is used in case the building is in a Lost City sphere
	#Range: 0.0 ~ 1.0
	sphereHauntedChance = 0.700000011920929
	#The minimum amount of mobs that are spawned by a haunted building. This version is used in case the building is in a Lost City sphere
	#Range: 1 ~ 10000
	sphereMinMobs = 4
	#The maximum amount of mobs that are spawned by a haunted building. This version is used in case the building is in a Lost City sphere
	#Range: 1 ~ 10000
	sphereMaxMobs = 8
	#If this is true then mobs will only spawn if the light level is low enough. Otherwise they spawn regardless of light level
	checkValidSpawn = false
	#If this is true then the player will be notified when a building is cleared
	announceCleared = true
	#If this is true then the player will be notified when he or she enters a haunted building
	announceEnter = true
	#If this is true then the player will get a message when he/she tries to open a locked chest
	announceChestLocked = true
	#If this is true then all chests will be locked until the building is cleared
	lockChestsUntilCleared = true
	#This option is only useful when 'lockChestsUntilCleared'. If true only vanilla chests will be locked. Otherwise all tile entities are locked
	lockOnlyChests = true

