#Restock
Restock = true
#Use fixed items
UseFixedItems = false
#Minable
Minable = false
#Fixed items; item or item,amount,pay_item,cost,uses
FixedItems = ["minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air", "minecraft:air"]
#Include Mods
IncludeMods = ["zombiekit", "sewingkit", "iwannaskate", "hmag", "exnihilosequentia", "farmersdelight", "minecraft", "resourceful_tools", "supplementaries", "opolisutilities", "mca", "clickmachine", "bagofholding", "craftingautomat"]
#Exclude Mods
ExcludeMods = ["toms_storage", "scuba_gear", "rottencreatures", "quark", "platforms", "nameless_trinkets", "obscure_api", "itemfilters", "immersive_paintings", "horrors_of_october"]
#Include Items
IncludeItems = ["zombiekit:serum_bottle", "zombiekit:serum_needle_tubing", "zombiekit:studded_baseball_bat", "zombiekit:fire_axe_broken", "zombiekit:crowbar_broken", "zombiekit:cloth", "zombiekit:baseball_bat_broken", "sewingkit:iron_sewing_needle", "zombiekit:machete", "zombiekit:mirror_suspicious_medicine", "zombiekit:camphor", "zombiekit:alcohol", "zombiekit:hydrogen_nitrate", "resourceful_tools:jerky", "supplementaries:rope_arrow", "opolisutilities:redstone_clock", "opolisutilities:jerky", "mca:book_blueprint", "mca:needle_and_thread", "mca:comb", "iwannaskate:energy_drink", "iwannaskate:pizza_slice", "hmag:randomberry", "hmag:cureberry", "craftingautomat:autocrafter", "bagofholding:leather_bag_of_holding", "clickmachine:auto_clicker"]
#Exclude Items
ExcludeItems = ["minecraft:nether_star", "minecraft:beacon", "minecraft:bedrock", "minecraft:shulker_box", "minecraft:colorset*shulker_box", "minecraft:elytra", "minecraft:end_portal_frame", "minecraft:armorset*netherite", "minecraft:toolset*netherite", "minecraft:netherite_block", "minecraft:netherite_ingot", "vm:vending_machine"]
#Include Creative Tab Groups
IncludeGroups = ["*"]
#Exclude Creative Tab Groups
ExcludeGroups = ["!"]
#Change item rarity value for pricing
ItemRarity = ["minecraft:emerald_block=1", "minecraft:diamond_block=1", "minecraft:armorset*diamond=1", "minecraft:toolset*diamond=1", "minecraft:anvil=2", "minecraft:trident=3", "minecraft:bell=2", "minecraft:conduit=3", "minecraft:nautilus_shell=1", "eggset*peaceful=1", "eggset*monster=2", "minecraft:evoker_spawn_egg=3", "minecraft:netherite_scrap=2", "minecraft:ancient_debris=2", "minecraft:axolotl_bucket=1"]

[RarityData]
	#Common Item
	CommonItem = "opolisutilities:b_bucks"
	#Uncommon Item
	UncommonItem = "opolisutilities:b_bucks"
	#Rare Item
	RareItem = "opolisutilities:b_bucks"
	#Epic Item
	EpicItem = "opolisutilities:b_bucks"
	#Common Cost
	#Range: 0 ~ 64
	CommonCost = 1
	#Uncommon Cost
	#Range: 0 ~ 64
	UncommonCost = 16
	#Rare Cost
	#Range: 0 ~ 64
	RareCost = 32
	#Epic Cost
	#Range: 0 ~ 64
	EpicCost = 64
	#Common Uses
	#Range: 0 ~ 32
	CommonUses = 8
	#Uncommon Uses
	#Range: 0 ~ 32
	UncommonUses = 4
	#Rare Uses
	#Range: 0 ~ 32
	RareUses = 2
	#Epic Uses
	#Range: 0 ~ 32
	EpicUses = 1

